name: goreleaser

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches: ['master']
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: set up CycloneDX
        uses: CycloneDX/gh-gomod-generate-sbom@v1
        with:
          version: v1
      -
        name: spdx
        uses: actions/checkout@v2
        with:
          fetch-depth: 0        
      -
        name: run GoReleaser
        uses: goreleaser/goreleaser-action@v2.4.1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
      -
        name: spdx
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
